<?php
/**
 * Template Name: OSCAL Control Layout
 * Template Post Type: security_control, oscal_control
 *
 * This template intentionally renders the post’s block content as-is.
 * Customize by copying this file into your (child) theme root as `oscal-control.php`
 * or into `your-theme/templates/oscal-control.php`. The plugin will prefer the theme version.
 */
if (!defined('ABSPATH')) exit;

get_header();
?>
<main id="primary" class="site-main oscal-control-template">
    <?php
    if (have_posts()) :
        while (have_posts()) : the_post();
            // Title (already includes zero-padded label in your importer)
            echo '<header class="oscal-control-header alignwide">';
            echo '<h1 class="entry-title">' . esc_html(get_the_title()) . '</h1>';
            echo '</header>';

            // Content (block markup generated by importer)
            echo '<div class="entry-content">';
            the_content();
            echo '</div>';
        endwhile;
    endif;
    ?>
</main>
<?php get_footer(); ?>
